<section class="config-panel" data-panel="comercio">
  <form method="POST" action="index.php?c=configuracion&a=guardar" enctype="multipart/form-data">
    <input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="comercio">
    <div class="config-panel-head"><div><h4>Comercio</h4><p>Fuente unica para navbar, tickets, PDF, reportes y vistas previas.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-danger" form="reset-comercio" type="submit">Restablecer</button><button class="btn btn-primary" type="submit">Guardar cambios</button></div></div>
    <div class="config-grid">
      <div class="config-block"><h5>Identificacion</h5><label class="form-label">Nombre comercio</label><input class="form-control live-input" data-preview-text="#previewBrand" name="config[nombre_comercio]" value="<?= cfg_get($config, "nombre_comercio", "MI COMERCIO") ?>"><label class="form-label mt-3">Razon social</label><input class="form-control" name="config[razon_social]" value="<?= cfg_get($config, "razon_social") ?>"><label class="form-label mt-3">CUIT</label><input class="form-control" name="config[cuit]" value="<?= cfg_get($config, "cuit") ?>"><label class="form-label mt-3">IVA</label><select class="form-select" name="config[condicion_iva]"><?php foreach (["", "Responsable Inscripto", "Monotributista", "Exento", "Consumidor Final", "No Responsable"] as $op): ?><option value="<?= htmlspecialchars($op) ?>" <?= cfg_select($config, "condicion_iva", $op) ?>><?= $op === "" ? "Seleccionar" : htmlspecialchars($op) ?></option><?php endforeach; ?></select></div>
      <div class="config-block"><h5>Ubicacion</h5><label class="form-label">Direccion</label><input class="form-control" name="config[domicilio]" value="<?= cfg_get($config, "domicilio") ?>"><label class="form-label mt-3">Localidad</label><input class="form-control" name="config[localidad]" value="<?= cfg_get($config, "localidad") ?>"><label class="form-label mt-3">Provincia</label><input class="form-control" name="config[provincia]" value="<?= cfg_get($config, "provincia") ?>"></div>
      <div class="config-block"><h5>Contacto</h5><label class="form-label">Telefono</label><input class="form-control" name="config[telefonos]" value="<?= cfg_get($config, "telefonos") ?>"><label class="form-label mt-3">WhatsApp</label><input class="form-control" name="config[whatsapp]" value="<?= cfg_get($config, "whatsapp") ?>"><label class="form-label mt-3">Email</label><input class="form-control" type="email" name="config[email]" value="<?= cfg_get($config, "email") ?>"></div>
    </div>
  </form>
  <form id="reset-comercio" method="POST" action="index.php?c=configuracion&a=restablecer"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="comercio"></form>
</section>
