<section class="config-panel" data-panel="impresion">
  <form method="POST" action="index.php?c=configuracion&a=guardar" enctype="multipart/form-data">
    <input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="impresion">
    <div class="config-panel-head"><div><h4>Impresion</h4><p>Formato, tipografia, pie y logo del ticket. Los datos del comercio se toman de Comercio.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-danger" form="reset-impresion" type="submit">Restablecer</button><button class="btn btn-primary" type="submit">Guardar cambios</button></div></div>
    <div class="config-grid">
      <div class="config-block"><h5>Formato</h5><select class="form-select live-ticket-format" name="config[formato_impresion_ticket]"><option value="58" <?= cfg_select($config, "formato_impresion_ticket", "58") ?>>Ticket 58mm</option><option value="80" <?= cfg_select($config, "formato_impresion_ticket", "80", "80") ?>>Ticket 80mm</option><option value="a4" <?= cfg_select($config, "formato_impresion_ticket", "a4") ?>>A4</option></select><label class="form-label mt-3">Fuente</label><select class="form-select live-ticket-font" name="config[ticket_fuente]"><?php foreach (["Arial", "Verdana", "Courier New", "Tahoma"] as $fuente): ?><option value="<?= htmlspecialchars($fuente) ?>" <?= cfg_select($config, "ticket_fuente", $fuente, "Arial") ?>><?= htmlspecialchars($fuente) ?></option><?php endforeach; ?></select><label class="form-label mt-3">Tamano fuente</label><input type="range" min="10" max="18" class="form-range live-ticket-size" name="config[ticket_tamano_fuente]" value="<?= cfg_get($config, "ticket_tamano_fuente", "12") ?>"></div>
      <div class="config-block"><h5>Contenido</h5><label class="form-label">Mensaje pie</label><textarea class="form-control live-input" data-preview-text="#ticketFooter" name="config[texto_pie_ticket]" rows="2"><?= cfg_get($config, "texto_pie_ticket", "Gracias por su compra") ?></textarea><label class="form-label mt-3">Logo ticket <span class="text-muted" title="Compatible con termicas">ⓘ</span></label><input class="form-control" type="file" name="logo_ticket_archivo" accept=".jpg,.jpeg,.png,.gif,.webp"><div class="form-check form-switch mt-3"><input class="form-check-input" type="checkbox" name="config[ticket_logo_termico]" value="1" <?= cfg_checked($config, "ticket_logo_termico", "1") ?>><label class="form-check-label">Optimizar logo termico</label></div><div class="form-check form-switch mt-2"><input class="form-check-input" type="checkbox" name="config[ticket_imagen_completa]" value="1" <?= cfg_checked($config, "ticket_imagen_completa") ?>><label class="form-check-label">La imagen contiene datos del comercio</label></div></div>
    </div>
  </form>
  <form id="reset-impresion" method="POST" action="index.php?c=configuracion&a=restablecer"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="impresion"></form>
</section>
