<section class="config-panel" data-panel="productos">
  <form method="POST" action="index.php?c=configuracion&a=guardar">
    <input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="productos">
    <div class="config-panel-head"><div><h4>Productos</h4><p>Importaciones, codigo de barras, stock y reglas automaticas.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-danger" form="reset-productos" type="submit">Restablecer</button><button class="btn btn-primary" type="submit">Guardar cambios</button></div></div>
    <div class="config-grid">
      <div class="config-block"><div class="d-flex align-items-center gap-2 mb-3"><div class="icon-circle"><i class="bi bi-box-seam-fill"></i></div><h5 class="mb-0">Reglas</h5></div><?php foreach (["productos_multiples_listas" => "Activar multiples listas", "productos_mostrar_stock_minimo" => "Mostrar stock minimo", "productos_permitir_stock_negativo" => "Permitir stock negativo", "productos_activar_escaner" => "Activar escaner", "productos_etiquetas" => "Etiquetas", "productos_importacion_excel" => "Importacion Excel", "productos_reglas_automaticas" => "Reglas automaticas"] as $clave => $txt): ?><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[<?= htmlspecialchars($clave) ?>]" value="1" <?= cfg_checked($config, $clave, "1") ?>><label class="form-check-label"><i class="bi bi-check-circle-fill"></i> <?= htmlspecialchars($txt) ?></label></div><?php endforeach; ?></div>
      <div class="config-block"><div class="d-flex align-items-center gap-2 mb-3"><div class="icon-circle"><i class="bi bi-upc-scan"></i></div><h5 class="mb-0">Codigo de barras</h5></div><label class="form-label"><div class="campo-icon"><i class="bi bi-upc"></i></div> Formato</label><select class="form-select" name="config[productos_formato_codigo_barras]"><option value="ean13" <?= cfg_select($config, "productos_formato_codigo_barras", "ean13", "ean13") ?>>EAN-13</option><option value="code128" <?= cfg_select($config, "productos_formato_codigo_barras", "code128") ?>>Code 128</option><option value="interno" <?= cfg_select($config, "productos_formato_codigo_barras", "interno") ?>>Interno</option></select><label class="form-label mt-3"><div class="campo-icon"><i class="bi bi-123"></i></div> PLU digitos balanza</label><input type="number" min="1" max="8" class="form-control" name="config[balanza_plu_digitos]" value="<?= cfg_get($config, "balanza_plu_digitos", "5") ?>"></div>
    </div>
  </form>
  <form id="reset-productos" method="POST" action="index.php?c=configuracion&a=restablecer"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="productos"></form>
</section>
