<section class="config-panel" data-panel="seguridad">
  <form method="POST" action="index.php?c=configuracion&a=guardar">
    <input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="seguridad">
    <div class="config-panel-head"><div><h4>Seguridad</h4><p>Sesiones, acceso, bloqueos, permisos y logs.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-danger" form="reset-seguridad" type="submit">Restablecer</button><button class="btn btn-primary" type="submit">Guardar cambios</button></div></div>
    <div class="config-grid">
      <div class="config-block"><h5>Sesion</h5><label class="form-label">Tiempo sesion minutos</label><input type="number" min="5" max="1440" class="form-control" name="config[seguridad_tiempo_sesion]" value="<?= cfg_get($config, "seguridad_tiempo_sesion", "120") ?>"><label class="form-label mt-3">Modo de acceso</label><select class="form-select" name="config[auth_modo]"><option value="login" <?= cfg_select($config, "auth_modo", "login", "login") ?>>Con usuario y contrasena</option><option value="sin_login" <?= cfg_select($config, "auth_modo", "sin_login") ?>>Entrar sin pedir nada</option></select></div>
      <div class="config-block"><h5>Controles</h5><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[seguridad_2fa_futuro]" value="1" <?= cfg_checked($config, "seguridad_2fa_futuro") ?>><label class="form-check-label">Doble autenticacion futura</label></div><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[seguridad_bloqueos]" value="1" <?= cfg_checked($config, "seguridad_bloqueos", "1") ?>><label class="form-check-label">Bloqueos</label></div><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[seguridad_logs]" value="1" <?= cfg_checked($config, "seguridad_logs", "1") ?>><label class="form-check-label">Logs</label></div><label class="form-label mt-2">IP permitidas</label><textarea class="form-control" name="config[seguridad_ips_permitidas]" rows="3"><?= cfg_get($config, "seguridad_ips_permitidas") ?></textarea></div>
    </div>
  </form>
  <form id="reset-seguridad" method="POST" action="index.php?c=configuracion&a=restablecer"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="seguridad"></form>
</section>
