<section class="config-panel" data-panel="ventas">
  <form method="POST" action="index.php?c=configuracion&a=guardar">
    <input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="ventas">
    <div class="config-panel-head"><div><h4>Ventas</h4><p>Opciones de venta, descuentos, confirmaciones y estados.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-danger" form="reset-ventas" type="submit">Restablecer</button><button class="btn btn-primary" type="submit">Guardar cambios</button></div></div>
    <div class="config-grid">
      <div class="config-block"><h5><i class="bi bi-sliders"></i> Operacion</h5><label class="form-label"><i class="bi bi-123"></i> Cantidad decimal</label><div class="input-group"><span class="input-group-text"><i class="bi bi-123"></i></span><input type="number" min="0" max="4" class="form-control" name="config[ventas_cantidad_decimales]" value="<?= cfg_get($config, "ventas_cantidad_decimales", "3") ?>"></div><label class="form-label mt-2"><i class="bi bi-percent"></i> Descuento automatico %</label><div class="input-group"><span class="input-group-text"><i class="bi bi-percent"></i></span><input type="number" min="0" max="100" class="form-control" name="config[ventas_descuento_automatico]" value="<?= cfg_get($config, "ventas_descuento_automatico", "0") ?>"></div><label class="form-label mt-2"><i class="bi bi-person-fill"></i> Cliente por defecto</label><div class="input-group"><span class="input-group-text"><i class="bi bi-person-fill"></i></span><input class="form-control" name="config[ventas_cliente_defecto]" value="<?= cfg_get($config, "ventas_cliente_defecto", "Consumidor Final") ?>"></div></div>
      <div class="config-block"><h5><i class="bi bi-cpu-fill"></i> Comportamiento</h5><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[ventas_rapidas]" value="1" <?= cfg_checked($config, "ventas_rapidas", "1") ?>><label class="form-check-label"><i class="bi bi-lightning-fill"></i> Ventas rapidas</label></div><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[ventas_consumidor_final_auto]" value="1" <?= cfg_checked($config, "ventas_consumidor_final_auto", "1") ?>><label class="form-check-label"><i class="bi bi-person-check-fill"></i> Consumidor Final automatico</label></div><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[ventas_confirmar_cierre]" value="1" <?= cfg_checked($config, "ventas_confirmar_cierre", "1") ?>><label class="form-check-label"><i class="bi bi-question-circle-fill"></i> Preguntar antes de cerrar venta</label></div><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[ventas_sonido_confirmacion]" value="1" <?= cfg_checked($config, "ventas_sonido_confirmacion", "1") ?>><label class="form-check-label"><i class="bi bi-volume-up-fill"></i> Confirmacion sonora</label></div><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="config[controlar_stock_ventas]" value="1" <?= cfg_checked($config, "controlar_stock_ventas", "1") ?>><label class="form-check-label"><i class="bi bi-box-fill"></i> Controlar stock al vender</label></div></div>
      <div class="config-block"><h5><i class="bi bi-palette2"></i> Color de estados</h5><div class="color-grid"><label>Pendiente<input type="color" class="form-control form-control-color" name="config[ventas_color_pendiente]" value="<?= cfg_color_mod($config, "ventas_color_pendiente", "#f59e0b") ?>"></label><label>Completada<input type="color" class="form-control form-control-color" name="config[ventas_color_completada]" value="<?= cfg_color_mod($config, "ventas_color_completada", "#16a34a") ?>"></label><label>Cancelada<input type="color" class="form-control form-control-color" name="config[ventas_color_cancelada]" value="<?= cfg_color_mod($config, "ventas_color_cancelada", "#dc2626") ?>"></label></div></div>
    </div>
  </form>
  <form id="reset-ventas" method="POST" action="index.php?c=configuracion&a=restablecer"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="seccion" value="ventas"></form>
</section>
